-- ACCESS ROLES
DEFINE ROLE AR_{{ env }}_ECOM_RAW_READ;
DEFINE ROLE AR_{{ env }}_ECOM_RAW_WRITE;

DEFINE ROLE AR_{{ env }}_ECOM_TRANSFORM_READ;
DEFINE ROLE AR_{{ env }}_ECOM_TRANSFORM_WRITE;

DEFINE ROLE AR_{{ env }}_ECOM_REPORTING_READ;
DEFINE ROLE AR_{{ env }}_ECOM_REPORTING_WRITE;

-- FUNCTIONAL ROLES
DEFINE ROLE FR_{{ env }}_ECOM_INGEST;
DEFINE ROLE FR_{{ env }}_ECOM_TRANSFORM;
DEFINE ROLE FR_{{ env }}_ECOM_REPORTING;