-- RAW READ
GRANT USAGE ON DATABASE {{ sf_db }} TO ROLE AR_{{ env }}_ECOM_RAW_READ;
GRANT USAGE ON SCHEMA {{ sf_db }}.RAW TO ROLE AR_{{ env }}_ECOM_RAW_READ;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ sf_db }}.RAW TO ROLE AR_{{ env }}_ECOM_RAW_READ;

-- RAW WRITE
GRANT ROLE AR_{{ env }}_ECOM_RAW_READ TO ROLE AR_{{ env }}_ECOM_RAW_WRITE;
GRANT CREATE TABLE ON SCHEMA {{ sf_db }}.RAW TO ROLE AR_{{ env }}_ECOM_RAW_WRITE;

-- FUNCTIONAL ROLES

----- INGEST: writes to RAW, reads TRANSFORM (to check dependencies)
GRANT ROLE AR_{{ env }}_ECOM_RAW_WRITE TO ROLE FR_{{ env }}_ECOM_INGEST;
GRANT ROLE AR_{{ env }}_ECOM_TRANSFORM_READ TO ROLE FR_{{ env }}_ECOM_INGEST;

---TRANSFORM: reads RAW, writes to TRANSFORM
GRANT ROLE AR_{{ env }}_ECOM_RAW_READ TO ROLE FR_{{ env }}_ECOM_TRANSFORM;
GRANT ROLE AR_{{ env }}_ECOM_TRANSFORM_WRITE TO ROLE FR_{{ env }}_ECOM_TRANSFORM;

----- REPORTING: reads TRANSFORM, writes to REPORTING
GRANT ROLE AR_{{ env }}_ECOM_TRANSFORM_READ TO ROLE FR_{{ env }}_ECOM_REPORTING;
GRANT ROLE AR_{{ env }}_ECOM_REPORTING_WRITE TO ROLE FR_{{ env }}_ECOM_REPORTING;

-- ADMIN ACCESS(All functional roles roll up to ECOM_DCM_ADMIN)
GRANT ROLE FR_{{ env }}_ECOM_INGEST TO ROLE ECOM_DCM_ADMIN;
GRANT ROLE FR_{{ env }}_ECOM_TRANSFORM TO ROLE ECOM_DCM_ADMIN;
GRANT ROLE FR_{{ env }}_ECOM_REPORTING TO ROLE ECOM_DCM_ADMIN;