-- new change to trigger pipeline
DEFINE SCHEMA {{ sf_db }}.RAW;
DEFINE SCHEMA {{ sf_db }}.TRANSFORM;
DEFINE SCHEMA {{ sf_db }}.REPORTING;

-- RAW TABLES
DEFINE TABLE {{ sf_db }}.RAW.CUSTOMERS (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    CITY VARCHAR,
    CREATED_AT TIMESTAMP
);

DEFINE TABLE {{ sf_db }}.RAW.PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(10,2)
);

DEFINE TABLE {{ sf_db }}.RAW.ORDERS (
    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_DATE TIMESTAMP,
    TOTAL_AMOUNT NUMBER(10,2)
);

DEFINE TABLE {{ sf_db }}.RAW.ORDER_ITEMS (
    ORDER_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    QUANTITY NUMBER,
    PRICE NUMBER(10,2)
);

-- TRANSFORM
DEFINE TABLE {{ sf_db }}.TRANSFORM.ORDER_SUMMARY (
    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    TOTAL_ITEMS NUMBER,
    TOTAL_AMOUNT NUMBER(10,2)
);

-- REPORTING
DEFINE TABLE {{ sf_db }}.REPORTING.SALES_METRICS (
    CUSTOMER_ID VARCHAR,
    TOTAL_ORDERS NUMBER,
    TOTAL_SPENT NUMBER(10,2)
);

DEFINE TABLE {{ sf_db }}.RAW.ORDERS_NEW (
  ID NUMBER,
  AMOUNT NUMBER
);

DEFINE TABLE {{ sf_db }}.RAW.TEST_TABLE (
  ID INT
);

-- New change to trigger pipeline (meaningful addition)
DEFINE TABLE {{ sf_db }}.RAW.PAYMENTS (
    PAYMENT_ID VARCHAR,
    ORDER_ID VARCHAR,
    PAYMENT_METHOD VARCHAR,
    PAYMENT_STATUS VARCHAR,
    PAYMENT_DATE TIMESTAMP,
    AMOUNT NUMBER(10,2)
);