name: DCM Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli

      # ✅ CREATE KEY FIRST
      - name: Create Private Key File
        run: |
          echo "${{ secrets.SF_PRIVATE_KEY }}" > key.p8

      # ✅ THEN USE KEY
      - name: Configure Snowflake Connection
        run: |
          snow connection add ci_conn \
            --account ${{ secrets.SF_ACCOUNT }} \
            --user ${{ secrets.SF_USER }} \
            --private-key-path key.p8 \
            --role ECOM_DCM_ADMIN \
            --warehouse COMPUTE_WH \
            --database DEV_SF_DB \
            --schema PUBLIC

      - name: Deploy DCM Project
        run: |
          snow sql -q "
          EXECUTE DCM PROJECT DEV_SF_DB.PUBLIC.ECOMMERCE_DCM_DEV
          DEPLOY AS 'ci cd deployment'
          USING CONFIGURATION dev
          FROM @ECOM_DCM_REPO/branches/main/;
          "
