name: DCM Plan on PR

on:
  pull_request:
    branches: [main]

jobs:
  plan:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
      SNOWFLAKE_ROLE: ECOM_DCM_ADMIN
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH

    steps:
      - uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0

      - name: Fetch Repo
        run: |
          snow sql -q "
          ALTER GIT REPOSITORY INTEGRATIONS.GITHUB.ECOM_DCM_REPO FETCH;
          " -x

      - name: Run PLAN
        run: |
          snow sql -q "
          EXECUTE DCM PROJECT DEV_SF_DB.PUBLIC.ECOMMERCE_DCM_DEV
          PLAN USING CONFIGURATION dev
          FROM @INTEGRATIONS.GITHUB.ECOM_DCM_REPO/branches/${{ github.head_ref }}/;
          " -x
