name: DCM Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
      SNOWFLAKE_ROLE: ECOM_DCM_ADMIN
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH
      SNOWFLAKE_DATABASE: DEV_SF_DB        # ✅ FIX
      SNOWFLAKE_SCHEMA: PUBLIC             # ✅ FIX

    steps:
      - uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0

      - name: Fetch Git Repo
        run: |
          snow sql -q "
          ALTER GIT REPOSITORY INTEGRATIONS.GITHUB.ECOM_DCM_REPO FETCH;
          " -x

      - name: Plan DEV
        run: |
          snow sql -q "
          EXECUTE DCM PROJECT DEV_SF_DB.PUBLIC.ECOMMERCE_DCM_DEV
          PLAN USING CONFIGURATION dev
          FROM @INTEGRATIONS.GITHUB.ECOM_DCM_REPO/branches/main/;
          " -x

      - name: Deploy DEV
        run: |
          snow sql -q "
          EXECUTE DCM PROJECT DEV_SF_DB.PUBLIC.ECOMMERCE_DCM_DEV
          DEPLOY AS 'ci_cd_deployment'
          USING CONFIGURATION dev
          FROM @INTEGRATIONS.GITHUB.ECOM_DCM_REPO/branches/main/;
          " -x
